# yaml-language-server: $schema=./manifest-infra-schema.json
# INFRA
schema-version: v1
kind: manifest
metadata:
  name: my_infra                  #(único por Workspace)
  app-id: 11111-22222-33333-44444       #(único por Workspace)
  runtime-version: 1.0.0                #(versão API Runtime)

specs:
  type: infra

  plugins:
    - name: stack/ecs-task@v3                    #(applied plugin - para criação de um ECS Task)
      type: runtime
      inputs:
         memory: {context.memory}                #(pega do contexto por ambiente)
         port: {context.port}                    #(para todos os ambientes)
      connector:
         - name: <CONNECTOR NAME 1>              #(escolhido)
           type: ecs-cluster-conn

    - name: another_stack/dynamo-repository@v3   #(applied plugin - para criação de novo banco)
      type: runtime
      inputs:
      connector:
         - name: dynamo-conn                     #(interface)
           id: db1

    - name: another_stack/dynamo@v3              #(interface implementation)
      type: runtime
      id: db1
      inputs:
        table: my-table
        pk: pk
        sk: sk

    - name: another_stack/sqs-consumer@v3         #(applied plugin - para criação de nova fila)
      type: runtime
      inputs:
      connector:
         - name: sqs-conn                         #(interface)
           id: sqs1

    - name: another_stack/sqs@v3                  #(interface implementation)
      type: runtime
      id: sqs1
      inputs:
        queue-name: my-queue

    - name: another_stack/sqs-consumer@v3         #(applied plugin - fila existente)
      type: runtime
      inputs:
      connector:
         - name: <CONNECTOR NAME 1>               #(escolhido)
           type: sqs-conn
