# yaml-language-server: $schema=./manifest-app-schema.json
# INFR
schema-version: v1
kind: manifest
metadata:
  name: my_infra                                            #(único por Workspace)
  description: Descreva sua infra explicando sua finalidade
  stack: demo-create-studio1/demo-stack
  stack-version-id: 01GXHFTEJ891VARHYSGAD90K4N

spec:
  type: app
  infra-id: 11111-22222-33333-44444                         #(único por Workspace) [Opcional] * Só é criado após o registro do app

  plugins:
    - name: account/studio/stack/microservices@v3       #(applied plugin)
      plugin-version-id: 01GXGJXAFXDCYJEJ81KH67KJNT
      type: infra
      inputs: # Objeto Chave valor
        namespace: Teste
        container_image: image-teste
        port: '80'
        check_env: false
      inputs-envs: {} # Objeto com Objeto com Chave e Valor
      connectors: # Array de objeto com name e type
        - name: eks-conn-demo1
          type: aws-eks-conn

    - name: test/integration-test/dotnet-errorhandler-plugin@0.0.1 #(applied plugin)
      plugin-version-id: 01GWJASJ2S910MV4V0CK5J2GGG
      type: infra
      inputs: {} # Objeto Chave valor
      inputs-envs: # Objeto com Objeto com Chave e Valor
        domain:
          prd: https://www.test.com.br
          new: https://new.test.com.br
          dev: https://dev.test.com.br
      connectors: [] # Array de objeto com name e type

  global-inputs:  # Opcional
    project_name: Teste  

  global-computed-inputs: # Opcional
    project_type: Api  
    version: stackspot.rest
    package: StackSpot.Template.Rest
    framework: net6.0
