# yaml-language-server: $schema=./../infra-schema.json
#RUNTIME PLUGIN#

schema-version: v1
kind: plugin
metadata:
  name: ecs-task
  display-name: ECS Task
  description: ECS Task for ITI applications
  version: 1.0.0
spec:
  type: infra
  app-allowed: true
  generates:
    - connection-interface: aws-vpc-conn
  requires:
    - connection-interface: ecs-cluster-fargate-conn
    - connection-interface: aws-vpc-conn
  inputs:
    - label: Task Name
      type: text
      name: task-name
    - label: Task Memory ALloc
      type: number
      name: memory
    - label: Task Port
      type: number
      name: port
