name: "create-plugin"
description: Just a simple Template
type: scaffold
haveSample: false
programmatic: false
tags:
  - "create-plugin-scaffold"
inputs:

  # parameters always provided by stk create plugin
 
  - label: "name"
    type: text
    name: "plugin_name"

  - label: "Repository:"
    type: text
    name: "repository"
    required: False

  - label: "Add Repository"
    type: bool
    name: "add_repository"

  - label: "Connection Interface Generated"
    type: text
    name: "connection_interface"
    required: True
    items:
      - ecs-task-conn
      - ecs-cluster-fargate-conn
      - aws-vpc-conn
      - sqs-queue-conn
      - rds-conn
      - dynamodb-conn

  # parameters will be asked if not provided by stk create plugin options
  - label: "Version"
    type: text
    name: "version"
    default: "0.0.1"

  - label: "Plugin description:"
    type: text
    name: "plugin_description"
    default: "Describe your plugin explaining its purpose"



